INSERT INTO TB_CATEGORY (NAME, created_at) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (NAME, created_at) VALUES ('Eletronics', NOW());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Computers', NOW());

